In [2]:
import numpy as np

In [3]:
arr = np.array([1,2,3,4,5,6,7,8,9])
arr.mean()

5.0

In [4]:
%%time
arr = np.arange(1,100000)
arr.sum()

Wall time: 5.75 ms


704982704

In [6]:
# One Dimantion array
np.zeros([10])

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [7]:
# Two Dimantion array
np.zeros([10,10])

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [8]:
# Three Dimantion array
np.zeros([10,10,10])

array([[[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]

In [9]:
# Four Dimantion array
np.ones([10,10,10,10])

array([[[[1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.],
         ...,
         [1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.]],

        [[1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.],
         ...,
         [1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.]],

        [[1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.],
         ...,
         [1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.]],

        ...,

        [[1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.],
         ...,
         [1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.],
    

In [10]:
np.empty([3,3])

array([[0.0000000e+000, 0.0000000e+000, 0.0000000e+000],
       [0.0000000e+000, 0.0000000e+000, 7.1935958e-321],
       [1.5108610e-311, 1.5108610e-311, 1.5126483e-311]])

In [13]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [17]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [18]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [19]:
# number of Dimention(ndim)
np.ones([10,10,10]).ndim

3

In [20]:
np.ones([10,10,10]).shape

(10, 10, 10)

In [21]:
np.ones([10,10,10]).dtype

dtype('float64')

In [22]:
np.ones([10,10,10], dtype=np.int64).dtype

dtype('int64')

In [23]:
np.empty([10,10,10], dtype=np.int64)

array([[[                   0,                    0,
                            0,                    0,
                3061567326960,  3388382884113086978,
                3061553860784,  -722894064047118845,
                3061605915056,  8606146163595084290],
        [                   0,                    0,
                3061872884528,  8813839463334583302,
                            0,                    0,
                            0,                    0,
                3061605916272, -1301515573423775735],
        [                   0,                    0,
                            0,                    0,
                            0,                    0,
                            0,                    0,
                3061871026224,  1638386290490852366],
        [       3061553592240,  4918817840254102031,
                3061605920176,  7971841698709788687,
                3061634809648,  6289108254340362255,
                3061605920304, -15880449965

In [24]:
np.ones([10,10,10]).astype(np.int64).dtype

dtype('int64')

In [27]:
arr = np.array([1,2,3,4,5,6,7])

In [28]:
arr[1:6
]

array([2, 3, 4, 5, 6])

In [29]:
arr[1:6:2]

array([2, 4, 6])

In [33]:
arr = np.array([
    [1,2,3,4,5,6,7],
    [3,4,5,6,2,0,1],
    [2,3,5,6,7,8,9]])

In [31]:
arr.shape

(2, 7)

In [34]:
arr[2,3]

6

In [35]:
arr[:,1]

array([2, 4, 3])

In [37]:
arr[1:1,1]

array([], dtype=int32)